name: バグ報告
description: バグ修正 Issue をこのフォームで作成します
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # タイトル
        （ここに Issue のタイトルを記載してください）

  - type: markdown
    attributes:
      value: |
        以下のフォームに沿って、バグの詳細を日本語で記入してください。
        すべての PR は base: dev を必須とします。タイトル・概要の後追い変更は行わないでください。
  - type: textarea
    id: title_and_description
    attributes:
      label: バグタイトルと問題概要
      description: 最初にバグタイトルを記載し、その後に問題の詳細を記述してください
      placeholder: |
        バグタイトル: ○○機能で××が正常動作しない問題

        問題概要: どの機能のどの部分で問題が発生しているか、期待される動作と実際の動作の違いを具体的に説明してください。
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 再現手順
      description: 問題を再現するための具体的な手順
      placeholder: |
        1. 管理画面で○○を選択
        2. △△を入力
        3. 更新ボタンをクリック
        4. 結果: ××が表示されない（期待: ○○が表示される）
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: 現在の動作（問題のある動作）
      description: 実際に発生している問題の詳細
      placeholder: |
        - ✅ 正常に動作している機能
        - ❌ 問題のある機能（具体的にどのような問題か）
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待される動作
      description: 正常に動作した場合の期待される結果
      placeholder: |
        どのような動作が期待されるか、UIの表示内容や保存されるべきデータなどを具体的に記述
    validations:
      required: true
  - type: textarea
    id: technical_analysis
    attributes:
      label: 技術的分析
      description: 問題の原因と考えられる技術的要因
      placeholder: |
        ### 関連ファイル
        - ファイル名1 - 問題箇所の説明
        - ファイル名2 - 関連する処理

        ### 推定原因
        - 具体的な原因の推測
        - コードの問題点や不足している実装
    validations:
      required: true
  - type: textarea
    id: fix_scope
    attributes:
      label: 修正が必要な箇所
      description: 修正すべきファイルや機能の範囲
      placeholder: |
        ### 1. ファイル名（役割）
        - 修正内容の詳細

        ### 2. ファイル名（役割）
        - 修正内容の詳細
    validations:
      required: true
  - type: textarea
    id: impact_assessment
    attributes:
      label: 影響範囲
      description: 修正による他機能への影響と互換性
      placeholder: |
        ### 新機能追加 / 破壊的変更の有無
        - 既存機能への影響
        - データベーススキーマ変更の必要性
        - 後方互換性の維持

        ### テスト対象
        1. 修正対象機能のテスト
        2. 関連機能の回帰テスト
        3. 既存データの互換性テスト
    validations:
      required: true
  - type: textarea
    id: related_files
    attributes:
      label: 関連ファイル
      description: 修正に関わるファイルの一覧
      placeholder: |
        - ファイル名1 - 役割の説明
        - ファイル名2 - 役割の説明
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      options:
        - label: バグ修正実装（根本原因の解決）
        - label: セキュリティ検証（サニタイズ・エスケープ）
        - label: WordPress準拠確認（コーディング規約・権限チェック）
        - label: 国際化対応（翻訳関数・テキストドメイン）
        - label: 後方互換性テスト（既存データ）
        - label: 回帰テスト（既存機能への影響確認）
        - label: ブラウザ互換性テスト
        - label: プラグインレビューガイドライン適合確認
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## 重要事項
        - /.github/copilot-instructions.md の指示に基づく運用を コメントによる追加修正時でも 徹底
        - タイトルや概要、コメントはルールに則り 日本語 で投稿
        - 一度作成したプルリクエストのタイトルや概要の内容を追加修正に伴って変更することは 絶対に行わない
        - プルリクエストの機能追加、バグ修正に伴って正常動作している機能を損なわないように 細心の注意 を払う
        - すべての PR は base: dev（master 直は不可）
  - type: markdown
    attributes:
      value: |
        ## 参考
        - 関連仕様/資料（必要に応じて起票後に追記）
        - リポジトリ運用規約: .github/copilot-instructions.md