name: 機能追加（テンプレート）
description: 機能追加 Issue の空テンプレート
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        # タイトル
        ここに Issue のタイトルを直接記載してください

  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: 目的、背景、達成したいことを簡潔に記載
      placeholder: |
        目的、背景、達成したいことを記載してください
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: 要件
      description: |
        サブ見出し（### 見出し）と箇条書きを組み合わせて詳細化してください
        必須小項目: 機能仕様、UI/文言、互換性/移行、実装影響範囲、テスト観点
      placeholder: |
        ### 機能仕様
        挙動、フォールバック、境界ケースを箇条書きで詳細化

        ### UI/文言
        配置場所、入力要素、ラベル・ヘルプ・プレースホルダー、国際化対応を詳細化

        ### 互換性/移行
        既存挙動の維持、設定の切替、データ構造の変更を詳細化

        ### 実装影響範囲
        編集が必要なファイル/層（管理画面、フロントエンド、データ構造、翻訳）を詳細化

        ### テスト観点
        基本動作、境界ケース、権限・セキュリティ、互換性の受け入れ基準を詳細化
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: チェックリスト
      description: 実施する作業のチェックリスト（要件ごとに具体的な検証項目を記載してください）
      placeholder: |
        ## チェックリスト（記述例）
        ### 機能仕様
        - 機能の境界条件や例外処理の検証項目を記載
        ### UI/文言
        - UI上のラベルやヘルプ文、翻訳の検証項目を記載
        ### 互換性/移行
        - 既存データや設定の互換性検証項目を記載
        ### テスト観点
        - ユニットテスト／回帰テスト／ブラウザ互換性の観点を記載
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## チェックリスト
        - [ ]
        
        **注意：チェックリストの記載は必須です。要件に応じた具体的な検証項目を `- [ ]` の形式で必ず記載してください。**

  - type: markdown
    attributes:
      value: |
        ## 重要事項
        以下の運用ルールを遵守してください。
        - /.github/copilot-instructions.md の指示に基づく運用を コメントによる追加修正時でも 徹底
        - タイトルや概要、コメントはルールに則り 日本語 で投稿
        - 一度作成したプルリクエストのタイトルや概要の内容を追加修正に伴って変更することは 絶対に行わない
        - report_progress ツールの prDescription パラメータはプルリクエスト初回作成時のみ使用すること
        - プルリクエストの機能追加、バグ修正に伴って正常動作している機能を損なわないように 細心の注意 を払う
        - PR の base は必ず dev（master 直は不可）

  - type: markdown
    attributes:
      value: |
        ## 参考
        - ノベルゲーム仕様（「かまいたちの夜」等）
        - リポジトリ運用規約: .github/copilot-instructions.md
